test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,6 +2,7 @@ name: Build
 
 on:
   workflow_dispatch:
+  push:
 
 jobs:
   build:
@@ -13,30 +14,30 @@ jobs:
         target:
           - aarch64-unknown-linux-musl
           - arm-unknown-linux-musleabi
-          - arm-unknown-linux-musleabihf
-          - armv7-unknown-linux-musleabi
-          - armv7-unknown-linux-musleabihf
+          # - arm-unknown-linux-musleabihf
+          # - armv7-unknown-linux-musleabi
+          # - armv7-unknown-linux-musleabihf
           - i586-unknown-linux-musl
-          - i686-unknown-linux-musl
-          - i686-w64-mingw32
-          - loongarch64-unknown-linux-musl
-          - m68k-unknown-linux-musl
-          - microblazeel-xilinx-linux-musl
-          - microblaze-xilinx-linux-musl
-          - mipsel-unknown-linux-musl
+          # - i686-unknown-linux-musl
+          # - i686-w64-mingw32
+          # - loongarch64-unknown-linux-musl
+          # - m68k-unknown-linux-musl
+          # - microblazeel-xilinx-linux-musl
+          # - microblaze-xilinx-linux-musl
+          # - mipsel-unknown-linux-musl
           - mipsel-unknown-linux-muslsf
-          - mips-unknown-linux-musl
+          # - mips-unknown-linux-musl
           - mips-unknown-linux-muslsf
-          - mips64el-unknown-linux-musl
+          # - mips64el-unknown-linux-musl
           - mips64-unknown-linux-musl
           - powerpc-unknown-linux-musl
-          - powerpc64-unknown-linux-musl
-          - riscv32-unknown-linux-musl
-          - riscv64-unknown-linux-musl
-          - s390x-ibm-linux-musl
-          - sh-multilib-linux-musl
+          # - powerpc64-unknown-linux-musl
+          # - riscv32-unknown-linux-musl
+          # - riscv64-unknown-linux-musl
+          # - s390x-ibm-linux-musl
+          # - sh-multilib-linux-musl
           - x86_64-unknown-linux-musl
-          - x86_64-w64-mingw32
+          # - x86_64-w64-mingw32
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -58,8 +59,8 @@ jobs:
     needs: build
     permissions:
       contents: write
-    env:
-      tag_name: latest
+    # env:
+    #   tag_name: latest
     runs-on: ubuntu-latest
     steps:
       - name: Download artifacts
@@ -76,21 +77,22 @@ jobs:
             printf "| %s | %s |\n" "$i" $(sha256sum $i | awk '{print $1}') >> body.txt
           done
 
-      - name: Delete existing release
+      - name: GH
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           echo "DATE=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }} --jq '.commit.committer.date' | date -f - +%Y%m%d)" >> $GITHUB_ENV
-          gh release delete ${{ env.tag_name }} --cleanup-tag -y -R ${{ github.repository }} || true
+          # gh release delete ${{ env.tag_name }} --cleanup-tag -y -R ${{ github.repository }} || true
 
       - name: Upload release assets
         uses: softprops/action-gh-release@v2
         with:
           fail_on_unmatched_files: true
-          prerelease: false
+          prerelease: true
           draft: false
-          tag_name: ${{ env.tag_name }}
+          tag_name: ${{ env.DATE }}
           name: ${{ env.DATE }}
+          target_commitish: ${{ github.sha }}
           body_path: body.txt
           files: |
             *.tar.xz
